version: '3.8'

services:
  builder:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    volumes:
      - ./release:/usr/src/hardware_monitor/release

  hardware-monitor:
    build: .
    ports:
      - "${PORT:-9527}:9527"
    environment:
      - RUST_LOG=info
    restart: unless-stopped 