name: Build and Release

on:
  push:
    tags:
      - 'v*'
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1
  GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}

jobs:
  build:
    name: Build on ${{ matrix.os }} for ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          # Linux builds
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            artifact_suffix: linux-x86_64
            binary_name: hardware_monitor
          - os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
            artifact_suffix: linux-aarch64
            binary_name: hardware_monitor
            use_cross: true
          - os: ubuntu-latest
            target: armv7-unknown-linux-gnueabihf
            artifact_suffix: linux-armv7
            binary_name: hardware_monitor
            use_cross: true

          # Windows builds
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            artifact_suffix: windows-x86_64
            binary_name: hardware_monitor.exe
          - os: windows-latest
            target: i686-pc-windows-msvc
            artifact_suffix: windows-i686
            binary_name: hardware_monitor.exe

          # macOS builds
          - os: macos-latest
            target: x86_64-apple-darwin
            artifact_suffix: macos-x86_64
            binary_name: hardware_monitor
          - os: macos-latest
            target: aarch64-apple-darwin
            artifact_suffix: macos-aarch64
            binary_name: hardware_monitor

    steps:
    - uses: actions/checkout@v4

    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: ${{ matrix.target }}
        components: rustfmt, clippy

    - name: Install cross-compilation tools
      if: runner.os == 'Linux' && matrix.use_cross
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-aarch64-linux-gnu gcc-arm-linux-gnueabihf

    - name: Install Linux dependencies
      if: runner.os == 'Linux' && !matrix.use_cross
      run: |
        sudo apt-get update
        sudo apt-get install -y pkg-config libudev-dev

    - name: Install cross
      if: matrix.use_cross
      run: cargo install cross

    - name: Build with cross
      if: matrix.use_cross
      run: cross build --verbose --release --target ${{ matrix.target }}

    - name: Build native
      if: !matrix.use_cross
      run: cargo build --verbose --release --target ${{ matrix.target }}

    - name: Run tests
      if: !matrix.use_cross
      run: cargo test --verbose --target ${{ matrix.target }}

    - name: Package
      shell: bash
      run: |
        mkdir -p release
        cd target/${{ matrix.target }}/release
        if [[ "${{ matrix.binary_name }}" == *.exe ]]; then
          7z a ../../../release/hardware_monitor-${{ matrix.artifact_suffix }}.zip ${{ matrix.binary_name }}
          sha256sum ${{ matrix.binary_name }} > ../../../release/hardware_monitor-${{ matrix.artifact_suffix }}.sha256
        else
          tar czf ../../../release/hardware_monitor-${{ matrix.artifact_suffix }}.tar.gz ${{ matrix.binary_name }}
          sha256sum ${{ matrix.binary_name }} > ../../../release/hardware_monitor-${{ matrix.artifact_suffix }}.sha256
        fi
        cd ../../..

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: hardware_monitor-${{ matrix.artifact_suffix }}
        path: |
          release/hardware_monitor-${{ matrix.artifact_suffix }}.*
        retention-days: 5

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Create Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          name: Hardware Monitor ${{ github.ref }}
          body: |
            Hardware Monitor Release ${{ github.ref }}
            
            ## 下载
            ### Linux
            - [Linux x86_64](hardware_monitor-linux-x86_64.tar.gz)
            - [Linux ARM64](hardware_monitor-linux-aarch64.tar.gz)
            - [Linux ARMv7](hardware_monitor-linux-armv7.tar.gz)
            
            ### Windows
            - [Windows x64](hardware_monitor-windows-x86_64.zip)
            - [Windows x86](hardware_monitor-windows-i686.zip)
            
            ### macOS
            - [macOS x64](hardware_monitor-macos-x86_64.tar.gz)
            - [macOS ARM64](hardware_monitor-macos-aarch64.tar.gz)
            
            SHA256 校验和文件包含在每个发布包中。
          draft: false
          prerelease: false
          files: |
            artifacts/**/*.zip
            artifacts/**/*.tar.gz
            artifacts/**/*.sha256